# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kaio Magalhães
tagline:          'A Jekyll theme'
description:      'A software Engineer'
url:              http://kaiomagalhaes.com
baseurl:          /

author:
  name:           'Kaio Magalhães'
  url:            http://kaiomagalhaes.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kaiomagalhaes
